// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	message "kafka-exception-iterator/internal/message"

	mock "github.com/stretchr/testify/mock"
)

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

// Produce provides a mock function with given fields: _a0
func (_m *Producer) Produce(_a0 message.Message) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(message.Message) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
